### ISSUE TITLE
Fixing `Unsafe builtin usage fs.readFileSyn` error in Gatsby v3 

### ISSUE THREAD

**Issue by dewen** [johnsonandjohnson/Bodiless-JS#1101]
## Description
As a Developer, I want faster site builds both locally and on the cloud.

AC. Bodiless uses incremental builds

Fixing build warning accord to
https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#using-fs-in-ssr

Error log:
----
`warn Unsafe builtin method was used, future builds will need to rebuild all
warn WebpackError: Unsafe builtin usage fs.readFileSync:
@bodiless/test-site:     at packages/gatsby-plugin-ssi/read-ssi-entities.js:24:23
@bodiless/test-site:     at packages/gatsby-plugin-ssi/gatsby-ssr.js:32:23
@bodiless/test-site:     at @bodiless/test-site/.cache/api-runner-ssr.js:76:22
@bodiless/test-site:     at @bodiless/test-site/.cache/api-runner-ssr.js:69:3
@bodiless/test-site:     at @bodiless/test-site/.cache/static-entry.js:437:5
@bodiless/test-site:     at node_modules/@gatsbyjs/reach-router/es/lib/history.js:138:1
@bodiless/test-site:   22 |   const confPath = ssiConfPath || defaultSSIConfPath;
@bodiless/test-site:   23 |   try {
@bodiless/test-site: > 24 |     return JSON.parse(fs.readFileSync(confPath));
@bodiless/test-site:      |                       ^
@bodiless/test-site:   25 |   } catch (error) {
@bodiless/test-site:   26 |     // we need to log the error
`

### Steps to reproduce

- Run `npm run build`

Expected:
- no warning during built

Actual:
`Unsafe builtin method was used, future builds will need to rebuild all` found

Notes:
1. The fix should remove the warning message so incremental build is available during `gatsby build`
2. The SSI (bv script inclusion) should still work - adding `<!--# include virtual="/bv.html" -->` to every HTML page.

**Comment by dewen** [comment]
This prevent "incremental builds for HTML generation" in Gatsby v3 development, see
https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#using-fs-in-ssr
