### ISSUE TITLE
Cannot run Bodiless-JS in my Ubuntu 18.04

### ISSUE THREAD

**Issue by Sabir001** [johnsonandjohnson/Bodiless-JS#34]
## Description

Tried to run Bodiless-JS. Cloned the repo, ran 'npm install' and then ran 'npm run setup'. But, got some errors. Tried to run 'yarn setup', too. But, got same errors. 

```
npm ERR! bodiless-js@0.0.34 bootstrap: `lerna bootstrap --hoist && node scripts/postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bodiless-js@0.0.34 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Also here is the error log: 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'bootstrap' ]
2 info using npm@6.13.4
3 info using node@v10.18.1
4 verbose run-script [ 'prebootstrap', 'bootstrap', 'postbootstrap' ]
5 info lifecycle bodiless-js@0.0.34~prebootstrap: bodiless-js@0.0.34
6 info lifecycle bodiless-js@0.0.34~bootstrap: bodiless-js@0.0.34
7 warn lifecycle The node binary used for scripts is /tmp/yarn--1578979735716-0.5837744159527516/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
8 verbose lifecycle bodiless-js@0.0.34~bootstrap: unsafe-perm in lifecycle true
9 verbose lifecycle bodiless-js@0.0.34~bootstrap: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/sabir/Downloads/Bodiless-JS-master/node_modules/.bin:/tmp/yarn--1578979735716-0.5837744159527516:/home/sabir/Downloads/Bodiless-JS-master/node_modules/.bin:/home/sabir/.config/yarn/link/node_modules/.bin:/home/sabir/.yarn/bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle bodiless-js@0.0.34~bootstrap: CWD: /home/sabir/Downloads/Bodiless-JS-master
11 silly lifecycle bodiless-js@0.0.34~bootstrap: Args: [ '-c', 'lerna bootstrap --hoist && node scripts/postinstall' ]
12 silly lifecycle bodiless-js@0.0.34~bootstrap: Returned: code: 1  signal: null
13 info lifecycle bodiless-js@0.0.34~bootstrap: Failed to exec bootstrap script
14 verbose stack Error: bodiless-js@0.0.34 bootstrap: `lerna bootstrap --hoist && node scripts/postinstall`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:198:13)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:198:13)
14 verbose stack     at maybeClose (internal/child_process.js:982:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
15 verbose pkgid bodiless-js@0.0.34
16 verbose cwd /home/sabir/Downloads/Bodiless-JS-master
17 verbose Linux 5.0.0-37-generic
18 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "bootstrap"
19 verbose node v10.18.1
20 verbose npm  v6.13.4
21 error code ELIFECYCLE
22 error errno 1
23 error bodiless-js@0.0.34 bootstrap: `lerna bootstrap --hoist && node scripts/postinstall`
23 error Exit status 1
24 error Failed at the bodiless-js@0.0.34 bootstrap script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

```

### Steps to reproduce

1. Clone repo
2. Open directory
3. Open terminal and type 'npm install'
4. Then type 'npm run setup'

### Expected result

Setup should complete without issues

### Actual result

Some errors are occurring constantly.

### Environment

  System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.18.1 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 72.0.1
  npmGlobalPackages:
    gatsby-cli: 2.8.26

**Comment by hvanyo** [comment]
@Sabir001  can you try 'npm ci' instead of 'npm install'

**Comment by Sabir001** [comment]
@hvanyo thanks. The problem is solved. But, I did not see anything about `npm ci` in the docs.

**Comment by hvanyo** [comment]
@Sabir001  Thank you for your feedback and we are continuing to improve the documentation so its clear & concise.
