### ISSUE TITLE
missing asset EmptyFlowcontainer

### ISSUE THREAD

**Issue by malachye** [johnsonandjohnson/Bodiless-JS#867]
the following error is being thrown:
 
```
Building documentation tree
Error validating paths Error: ENOENT: no such file or directory, realpath '/Users/heidivanyo/slate/bodiless_starter/node_modules/@bodiless/layouts/assets/EmptyFlowcontainer.jpg'
    at Function.realpathSync.native (fs.js:1674:3)
    at /Users/heidivanyo/slate/bodiless_starter/node_modules/@bodiless/documentation/lib/tree.js:173:58
    at Array.forEach (<anonymous>)
    at Object.exports.validatePaths (/Users/heidivanyo/slate/bodiless_starter/node_modules/@bodiless/documentation/lib/tree.js:171:17)
    at /Users/heidivanyo/slate/bodiless_starter/node_modules/@bodiless/documentation/lib/blDocsBuild.js:143:28
    at step (/Users/heidivanyo/slate/bodiless_starter/node_modules/@bodiless/documentation/lib/blDocsBuild.js:77:23)
    at Object.next (/Users/heidivanyo/slate/bodiless_starter/node_modules/@bodiless/documentation/lib/blDocsBuild.js:58:53)
    at fulfilled (/Users/heidivanyo/slate/bodiless_starter/node_modules/@bodiless/documentation/lib/blDocsBuild.js:49:58) {
  errno: -2,
  syscall: 'realpath',
  code: 'ENOENT',
  path: '/Users/heidivanyo/slate/bodiless_starter/node_modules/@bodiless/layouts/assets/EmptyFlowcontainer.jpg'
}
Writing symlinks
Error writing symlinks [Error: ENOENT: no such file or directory, ensureSymlink '../../../node_modules/@bodiless/layouts/assets/EmptyFlowcontainer.jpg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '../../../node_modules/@bodiless/layouts/assets/EmptyFlowcontainer.jpg'
}

```

The fix is:
all assets folders should be in docs folder.
Update bodiless.docs.json paths.

**Comment by asiarheyeu** [comment]
Closed with PR #879
